name: Salud Para Hoy
favicon: null
layout_spectrum: 0.62279
typography_spectrum: 0.90953
title: Buena salud y bienestar
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#cda687'
    - '#c0dd1f'
    - '#fe8502'
    - '#a9100f'
  brandStrength: 0.8685169825330377
  lightness: 0.47020396078005433
  saturation: 0.9374665678478777
  rhythmicContrast: 0.4290120049845427
purpose: []
